# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:30:50+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class CompleteVerificationRequest(BaseModel):
    pin: Optional[str] = Field(
        None,
        description='Required. PIN code received by the merchant to complete the verification.',
    )


class RecommendationReason(Enum):
    RECOMMENDATION_REASON_UNSPECIFIED = 'RECOMMENDATION_REASON_UNSPECIFIED'
    BUSINESS_LOCATION_SUSPENDED = 'BUSINESS_LOCATION_SUSPENDED'
    BUSINESS_LOCATION_DISABLED = 'BUSINESS_LOCATION_DISABLED'


class ComplyWithGuidelines(BaseModel):
    recommendationReason: Optional[RecommendationReason] = Field(
        None,
        description='The reason why the location is being recommended to comply with guidelines.',
    )


class EmailVerificationData(BaseModel):
    domain: Optional[str] = Field(
        None,
        description='Domain name in the email address. e.g. "gmail.com" in foo@gmail.com',
    )
    isUserNameEditable: Optional[bool] = Field(
        None, description='Whether client is allowed to provide a different user name.'
    )
    user: Optional[str] = Field(
        None, description='User name in the email address. e.g. "foo" in foo@gmail.com'
    )


class PostalAddress(BaseModel):
    addressLines: Optional[List[str]] = Field(
        None,
        description='Unstructured address lines describing the lower levels of an address. Because values in address_lines do not have type information and may sometimes contain multiple values in a single field (e.g. "Austin, TX"), it is important that the line order is clear. The order of address lines should be "envelope order" for the country/region of the address. In places where this can vary (e.g. Japan), address_language is used to make it explicit (e.g. "ja" for large-to-small ordering and "ja-Latn" or "en" for small-to-large). This way, the most specific line of an address can be selected based on the language. The minimum permitted structural representation of an address consists of a region_code with all remaining information placed in the address_lines. It would be possible to format such an address very approximately without geocoding, but no semantic reasoning could be made about any of the address components until it was at least partially resolved. Creating an address only containing a region_code and address_lines, and then geocoding is the recommended way to handle completely unstructured addresses (as opposed to guessing which parts of the address should be localities or administrative areas).',
    )
    administrativeArea: Optional[str] = Field(
        None,
        description='Optional. Highest administrative subdivision which is used for postal addresses of a country or region. For example, this can be a state, a province, an oblast, or a prefecture. Specifically, for Spain this is the province and not the autonomous community (e.g. "Barcelona" and not "Catalonia"). Many countries don\'t use an administrative area in postal addresses. E.g. in Switzerland this should be left unpopulated.',
    )
    languageCode: Optional[str] = Field(
        None,
        description='Optional. BCP-47 language code of the contents of this address (if known). This is often the UI language of the input form or is expected to match one of the languages used in the address\' country/region, or their transliterated equivalents. This can affect formatting in certain countries, but is not critical to the correctness of the data and will never affect any validation or other non-formatting related operations. If this value is not known, it should be omitted (rather than specifying a possibly incorrect default). Examples: "zh-Hant", "ja", "ja-Latn", "en".',
    )
    locality: Optional[str] = Field(
        None,
        description='Optional. Generally refers to the city/town portion of the address. Examples: US city, IT comune, UK post town. In regions of the world where localities are not well defined or do not fit into this structure well, leave locality empty and use address_lines.',
    )
    organization: Optional[str] = Field(
        None, description='Optional. The name of the organization at the address.'
    )
    postalCode: Optional[str] = Field(
        None,
        description='Optional. Postal code of the address. Not all countries use or require postal codes to be present, but where they are used, they may trigger additional validation with other parts of the address (e.g. state/zip validation in the U.S.A.).',
    )
    recipients: Optional[List[str]] = Field(
        None,
        description='Optional. The recipient at the address. This field may, under certain circumstances, contain multiline information. For example, it might contain "care of" information.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='Required. CLDR region code of the country/region of the address. This is never inferred and it is up to the user to ensure the value is correct. See https://cldr.unicode.org/ and https://www.unicode.org/cldr/charts/30/supplemental/territory_information.html for details. Example: "CH" for Switzerland.',
    )
    revision: Optional[int] = Field(
        None,
        description='The schema revision of the `PostalAddress`. This must be set to 0, which is the latest revision. All new revisions **must** be backward compatible with old revisions.',
    )
    sortingCode: Optional[str] = Field(
        None,
        description='Optional. Additional, country-specific, sorting code. This is not used in most regions. Where it is used, the value is either a string like "CEDEX", optionally followed by a number (e.g. "CEDEX 7"), or just a number alone, representing the "sector code" (Jamaica), "delivery area indicator" (Malawi) or "post office indicator" (e.g. Côte d\'Ivoire).',
    )
    sublocality: Optional[str] = Field(
        None,
        description='Optional. Sublocality of the address. For example, this can be neighborhoods, boroughs, districts.',
    )


class ResolveOwnershipConflict(BaseModel):
    pass


class ServiceBusinessContext(BaseModel):
    address: Optional[PostalAddress] = Field(
        None,
        description='The verification address of the location. It is used to either enable more verification options or send a postcard.',
    )


class Method(Enum):
    VERIFICATION_METHOD_UNSPECIFIED = 'VERIFICATION_METHOD_UNSPECIFIED'
    ADDRESS = 'ADDRESS'
    EMAIL = 'EMAIL'
    PHONE_CALL = 'PHONE_CALL'
    SMS = 'SMS'
    AUTO = 'AUTO'
    VETTED_PARTNER = 'VETTED_PARTNER'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    PENDING = 'PENDING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class Verification(BaseModel):
    announcement: Optional[str] = Field(
        None,
        description='Optional. Response announcement set only if the method is VETTED_PARTNER.',
    )
    createTime: Optional[str] = Field(
        None, description='The timestamp when the verification is requested.'
    )
    method: Optional[Method] = Field(
        None, description='The method of the verification.'
    )
    name: Optional[str] = Field(None, description='Resource name of the verification.')
    state: Optional[State] = Field(None, description='The state of the verification.')


class VerificationMethod(Enum):
    VERIFICATION_METHOD_UNSPECIFIED = 'VERIFICATION_METHOD_UNSPECIFIED'
    ADDRESS = 'ADDRESS'
    EMAIL = 'EMAIL'
    PHONE_CALL = 'PHONE_CALL'
    SMS = 'SMS'
    AUTO = 'AUTO'
    VETTED_PARTNER = 'VETTED_PARTNER'


class VerificationToken(BaseModel):
    tokenString: Optional[str] = Field(None, description='The token string.')


class Verify(BaseModel):
    hasPendingVerification: Optional[bool] = Field(
        None,
        description='Indicates whether a verification process has already started, and can be completed by the location.',
    )


class VerifyLocationRequest(BaseModel):
    context: Optional[ServiceBusinessContext] = Field(
        None,
        description='Optional. Extra context information for the verification of service businesses. It is only required for the locations whose business type is CUSTOMER_LOCATION_ONLY. For ADDRESS verification, the address will be used to send out postcard. For other methods, it should be the same as the one that is passed to GetVerificationOptions. INVALID_ARGUMENT will be thrown if it is set for other types of business locations.',
    )
    emailAddress: Optional[str] = Field(
        None,
        description='Optional. The input for EMAIL method. Email address where the PIN should be sent to. An email address is accepted only if it is one of the addresses provided by FetchVerificationOptions. If the EmailVerificationData has is_user_name_editable set to true, the client may specify a different user name (local-part) but must match the domain name.',
    )
    languageCode: Optional[str] = Field(
        None,
        description='Optional. The BCP 47 language code representing the language that is to be used for the verification process.',
    )
    mailerContact: Optional[str] = Field(
        None,
        description='Optional. The input for ADDRESS method. Contact name the mail should be sent to.',
    )
    method: Optional[Method] = Field(None, description='Required. Verification method.')
    phoneNumber: Optional[str] = Field(
        None,
        description='Optional. The input for PHONE_CALL/SMS method The phone number that should be called or be sent SMS to. It must be one of the phone numbers in the eligible options.',
    )
    token: Optional[VerificationToken] = Field(
        None,
        description='Optional. The input for VETTED_PARTNER method available to select [partners.](https://support.google.com/business/answer/7674102) The input is not needed for a vetted account. Token that is associated to the location. Token that is associated to the location.',
    )


class VerifyLocationResponse(BaseModel):
    verification: Optional[Verification] = Field(
        None, description='The created verification request.'
    )


class WaitForVoiceOfMerchant(BaseModel):
    pass


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class AddressVerificationData(BaseModel):
    address: Optional[PostalAddress] = Field(
        None, description='Address that a postcard can be sent to.'
    )
    business: Optional[str] = Field(None, description="Merchant's business name.")
    expectedDeliveryDaysRegion: Optional[int] = Field(
        None,
        description="Expected number of days it takes to deliver a postcard to the address's region.",
    )


class CompleteVerificationResponse(BaseModel):
    verification: Optional[Verification] = Field(
        None, description='The completed verification.'
    )


class FetchVerificationOptionsRequest(BaseModel):
    context: Optional[ServiceBusinessContext] = Field(
        None,
        description='Optional. Extra context information for the verification of service businesses. Can only be applied to the locations whose business type is CUSTOMER_LOCATION_ONLY. Specifying an accurate address could enable more options. INVALID_ARGUMENT will be thrown if it is set for other business types of locations.',
    )
    languageCode: Optional[str] = Field(
        None,
        description='Required. The BCP 47 language code representing the language that is to be used for the verification process. Available options vary by language.',
    )


class GenerateVerificationTokenResponse(BaseModel):
    token: Optional[VerificationToken] = Field(
        None, description='The generated token to verify the location.'
    )


class ListVerificationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='If the number of verifications exceeded the requested page size, this field will be populated with a token to fetch the next page of verification on a subsequent call. If there are no more attributes, this field will not be present in the response.',
    )
    verifications: Optional[List[Verification]] = Field(
        None, description='List of the verifications.'
    )


class Location(BaseModel):
    address: Optional[PostalAddress] = Field(
        None,
        description='Required. A precise, accurate address to describe your business location. PO boxes or mailboxes located at remote locations are not acceptable. At this time, you can specify a maximum of five `address_lines` values in the address.',
    )
    name: Optional[str] = Field(
        None,
        description='Required. Location name should reflect your business\'s real-world name, as used consistently on your storefront, website, and stationery, and as known to customers. Any additional information, when relevant, can be included in other fields of the resource (for example, `Address`, `Categories`). Don\'t add unnecessary information to your name (for example, prefer "Google" over "Google Inc. - Mountain View Corporate Headquarters"). Don\'t include marketing taglines, store codes, special characters, hours or closed/open status, phone numbers, website URLs, service/product information, location/address or directions, or containment information (for example, "Chase ATM in Duane Reade").',
    )
    primaryCategoryId: Optional[str] = Field(
        None,
        description='Required. Id of the category that best describes the core business this location engages in. e.g. gcid:bakery.',
    )
    primaryPhone: Optional[str] = Field(
        None,
        description='Optional. A phone number that connects to your individual business location as directly as possible. Use a local phone number instead of a central, call center helpline number whenever possible.',
    )
    websiteUri: Optional[str] = Field(
        None,
        description='Optional. A URL for this business. If possible, use a URL that represents this individual business location instead of a generic website/URL that represents all locations, or the brand.',
    )


class VerificationOption(BaseModel):
    addressData: Optional[AddressVerificationData] = Field(
        None, description='Set only if the method is MAIL.'
    )
    announcement: Optional[str] = Field(
        None, description='Set only if the method is VETTED_PARTNER.'
    )
    emailData: Optional[EmailVerificationData] = Field(
        None, description='Set only if the method is EMAIL.'
    )
    phoneNumber: Optional[str] = Field(
        None,
        description='Set only if the method is PHONE_CALL or SMS. Phone number that the PIN will be sent to.',
    )
    verificationMethod: Optional[VerificationMethod] = Field(
        None, description='Method to verify the location.'
    )


class VoiceOfMerchantState(BaseModel):
    complyWithGuidelines: Optional[ComplyWithGuidelines] = Field(
        None,
        description='The location fails to comply with our [guidelines](https://support.google.com/business/answer/3038177) and requires additional steps for reinstatement. To fix this issue, consult the [Help Center Article](https://support.google.com/business/answer/4569145).',
    )
    hasBusinessAuthority: Optional[bool] = Field(
        None,
        description='Indicates whether the location has the authority (ownership) over the business on Google. If true, another location cannot take over and become the dominant listing on Maps. However, edits will not become live unless Voice of Merchant is gained (i.e. has_voice_of_merchant is true).',
    )
    hasVoiceOfMerchant: Optional[bool] = Field(
        None,
        description='Indicates whether the location is in good standing and has control over the business on Google. Any edits made to the location will propagate to Maps after passing the review phase.',
    )
    resolveOwnershipConflict: Optional[ResolveOwnershipConflict] = Field(
        None,
        description="This location duplicates another location that is in good standing. If you have access to the location in good standing, use that location's id to perform operations. Otherwise, request access from the current owner.",
    )
    verify: Optional[Verify] = Field(
        None, description='Start or continue the verification process.'
    )
    waitForVoiceOfMerchant: Optional[WaitForVoiceOfMerchant] = Field(
        None,
        description='Wait to gain Voice of Merchant. The location is under review for quality purposes.',
    )


class FetchVerificationOptionsResponse(BaseModel):
    options: Optional[List[VerificationOption]] = Field(
        None, description='The available verification options.'
    )


class GenerateVerificationTokenRequest(BaseModel):
    location: Optional[Location] = Field(
        None,
        description="Required. The target location. Note: The location information should exactly match the target Location, otherwise the generated verification token won't be able to verify the target Location.",
    )
